export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const ADD_PROPERTY = 'ADD_PROPERTY';
export const EDIT_PROPERTY = 'EDIT_PROPERTY';
export const SET_NAV_KEY = 'SET_NAV_KEY';
export const SET_PROPERTY = 'SET_PROPERTY';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const NO_PROPERTY = 'NO_PROPERTY';
export const REQUEST_NETWORK_ERROR = 'REQUEST_NETWORK_ERROR';
